
package ccm.server.ws.p6.export;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import javax.xml.namespace.QName;
import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 3.5.3
 * 2022-09-14T16:10:38.829+08:00
 * Generated source version: 3.5.3
 *
 */
public final class ExportPortType_ExportPort_Client {

    private static final QName SERVICE_NAME = new QName("http://xmlns.oracle.com/Primavera/P6/WS/WSExport/V2", "ExportService");

    private ExportPortType_ExportPort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = ExportService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        ExportService ss = new ExportService(wsdlURL, SERVICE_NAME);
        ExportPortType port = ss.getExportPort();

        {
        System.out.println("Invoking downloadFiles...");
        String _downloadFiles_jobType = "";
        java.util.List<String> _downloadFiles_jobName = null;
        javax.xml.datatype.XMLGregorianCalendar _downloadFiles_startDate = null;
        javax.xml.datatype.XMLGregorianCalendar _downloadFiles_endDate = null;
        try {
            int _downloadFiles__return = port.downloadFiles(_downloadFiles_jobType, _downloadFiles_jobName, _downloadFiles_startDate, _downloadFiles_endDate);
            System.out.println("downloadFiles.result=" + _downloadFiles__return);

        } catch (IntegrationFault e) {
            System.out.println("Expected exception: IntegrationFault has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking exportProject...");
        String _exportProject_encoding = "";
        ccm.server.ws.p6.export.FileTypeType _exportProject_fileType = null;
        ccm.server.ws.p6.export.LineSeparator _exportProject_lineSeparator = null;
        int _exportProject_projectObjectId = 0;
        ccm.server.ws.p6.export.SpreadPeriodType _exportProject_spreadPeriodType = null;
        String _exportProject_spacing = "";
        ccm.server.ws.p6.export.BusinessObjectOptions _exportProject_businessObjectOptions = null;
        try {
            javax.activation.DataHandler _exportProject__return = port.exportProject(_exportProject_encoding, _exportProject_fileType, _exportProject_lineSeparator, _exportProject_projectObjectId, _exportProject_spreadPeriodType, _exportProject_spacing, _exportProject_businessObjectOptions);
            System.out.println("exportProject.result=" + _exportProject__return);

        } catch (IntegrationFault e) {
            System.out.println("Expected exception: IntegrationFault has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking exportProjects...");
        String _exportProjects_encoding = "";
        ccm.server.ws.p6.export.FileTypeType _exportProjects_fileType = null;
        ccm.server.ws.p6.export.LineSeparator _exportProjects_lineSeparator = null;
        java.util.List<Integer> _exportProjects_projectObjectId = null;
        ccm.server.ws.p6.export.SpreadPeriodType _exportProjects_spreadPeriodType = null;
        String _exportProjects_spacing = "";
        ccm.server.ws.p6.export.BusinessObjectOptions _exportProjects_businessObjectOptions = null;
        try {
            javax.activation.DataHandler _exportProjects__return = port.exportProjects(_exportProjects_encoding, _exportProjects_fileType, _exportProjects_lineSeparator, _exportProjects_projectObjectId, _exportProjects_spreadPeriodType, _exportProjects_spacing, _exportProjects_businessObjectOptions);
            System.out.println("exportProjects.result=" + _exportProjects__return);

        } catch (IntegrationFault e) {
            System.out.println("Expected exception: IntegrationFault has occurred.");
            System.out.println(e.toString());
        }

            }

        System.exit(0);
    }

}
