
package ccm.server.ws.p6.export;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.5.3
 * 2022-09-14T16:10:38.878+08:00
 * Generated source version: 3.5.3
 */

@WebFault(name = "IntegrationFault", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/IntegrationFaultType/V1")
public class IntegrationFault extends Exception {

    private ccm.server.ws.p6.export.IntegrationFaultType faultInfo;

    public IntegrationFault() {
        super();
    }

    public IntegrationFault(String message) {
        super(message);
    }

    public IntegrationFault(String message, Throwable cause) {
        super(message, cause);
    }

    public IntegrationFault(String message, ccm.server.ws.p6.export.IntegrationFaultType integrationFault) {
        super(message);
        this.faultInfo = integrationFault;
    }

    public IntegrationFault(String message, ccm.server.ws.p6.export.IntegrationFaultType integrationFault, Throwable cause) {
        super(message, cause);
        this.faultInfo = integrationFault;
    }

    public ccm.server.ws.p6.export.IntegrationFaultType getFaultInfo() {
        return this.faultInfo;
    }
}
