package ccm.server.ws.p6.project;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.5.3
 * 2022-09-14T16:10:21.895+08:00
 * Generated source version: 3.5.3
 *
 */
@WebService(targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2", name = "ProjectPortType")
@XmlSeeAlso({ObjectFactory.class})
public interface ProjectPortType {

    @WebMethod(operationName = "DeleteProjects", action = "DeleteProjects")
    @RequestWrapper(localName = "DeleteProjects", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2", className = "ccm.server.ws.p6.project.DeleteProjects")
    @ResponseWrapper(localName = "DeleteProjectsResponse", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2", className = "ccm.server.ws.p6.project.DeleteProjectsResponse")
    @WebResult(name = "Return", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
    public boolean deleteProjects(

        @WebParam(name = "ObjectId", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        java.util.List<Integer> objectId
    ) throws IntegrationFault;

    @WebMethod(operationName = "PublishProject", action = "PublishProject")
    @RequestWrapper(localName = "PublishProject", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2", className = "ccm.server.ws.p6.project.PublishProject")
    @ResponseWrapper(localName = "PublishProjectResponse", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2", className = "ccm.server.ws.p6.project.PublishProjectResponse")
    @WebResult(name = "Return", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
    public boolean publishProject(

        @WebParam(name = "ObjectId", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        int objectId
    ) throws IntegrationFault;

    @WebMethod(operationName = "CopyWBSFromTemplate", action = "CopyWBSFromTemplate")
    @RequestWrapper(localName = "CopyWBSFromTemplate", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2", className = "ccm.server.ws.p6.project.CopyWBSFromTemplate")
    @ResponseWrapper(localName = "CopyWBSFromTemplateResponse", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2", className = "ccm.server.ws.p6.project.CopyWBSFromTemplateResponse")
    public void copyWBSFromTemplate(

        @WebParam(name = "ObjectId", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        int objectId,
        @WebParam(name = "TemplateWbsObjectId", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        int templateWbsObjectId,
        @WebParam(mode = WebParam.Mode.OUT, name = "ObjectId", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        javax.xml.ws.Holder<Integer> objectId1
    ) throws IntegrationFault;

    @WebMethod(operationName = "IsProjectLocked", action = "IsProjectLocked")
    @RequestWrapper(localName = "IsProjectLocked", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2", className = "ccm.server.ws.p6.project.IsProjectLocked")
    @ResponseWrapper(localName = "IsProjectLockedResponse", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2", className = "ccm.server.ws.p6.project.IsProjectLockedResponse")
    @WebResult(name = "Success", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
    public boolean isProjectLocked(

        @WebParam(name = "ObjectId", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        int objectId,
        @WebParam(name = "IncludeCurrentSession", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        boolean includeCurrentSession
    ) throws IntegrationFault;

    @WebMethod(operationName = "LoadActivityCodesNewerThanBaseline", action = "LoadActivityCodesNewerThanBaseline")
    @RequestWrapper(localName = "LoadActivityCodesNewerThanBaseline", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2", className = "ccm.server.ws.p6.project.LoadActivityCodesNewerThanBaseline")
    @ResponseWrapper(localName = "LoadActivityCodesNewerThanBaselineResponse", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2", className = "ccm.server.ws.p6.project.LoadActivityCodesNewerThanBaselineResponse")
    @WebResult(name = "ActivityCodeAssignmentObjectIds", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
    public java.util.List<String> loadActivityCodesNewerThanBaseline(

        @WebParam(name = "ObjectId", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        int objectId,
        @WebParam(name = "Fields", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        java.util.List<String> fields,
        @WebParam(name = "WhereClause", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        String whereClause,
        @WebParam(name = "OrderBy", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        String orderBy,
        @WebParam(name = "BaselineObjectId", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        int baselineObjectId
    ) throws IntegrationFault;

    @WebMethod(operationName = "ConvertProjectToBaseline", action = "ConvertProjectToBaseline")
    @RequestWrapper(localName = "ConvertProjectToBaseline", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2", className = "ccm.server.ws.p6.project.ConvertProjectToBaseline")
    @ResponseWrapper(localName = "ConvertProjectToBaselineResponse", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2", className = "ccm.server.ws.p6.project.ConvertProjectToBaselineResponse")
    @WebResult(name = "BaselineProjectObjectId", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
    public int convertProjectToBaseline(

        @WebParam(name = "OriginalProjectObjectId", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        int originalProjectObjectId,
        @WebParam(name = "TargetProjectObjectId", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        int targetProjectObjectId
    ) throws IntegrationFault;

    @WebMethod(operationName = "CreateProjectFromTemplate", action = "CreateProjectFromTemplate")
    @RequestWrapper(localName = "CreateProjectFromTemplate", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2", className = "ccm.server.ws.p6.project.CreateProjectFromTemplate")
    @ResponseWrapper(localName = "CreateProjectFromTemplateResponse", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2", className = "ccm.server.ws.p6.project.CreateProjectFromTemplateResponse")
    public void createProjectFromTemplate(

        @WebParam(name = "ObjectId", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        int objectId,
        @WebParam(name = "EPSObjectId", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        int epsObjectId,
        @WebParam(name = "CopyRisks", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        Boolean copyRisks,
        @WebParam(name = "CopyIssuesThresholds", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        Boolean copyIssuesThresholds,
        @WebParam(name = "CopyReports", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        Boolean copyReports,
        @WebParam(name = "CopyProjectDocuments", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        Boolean copyProjectDocuments,
        @WebParam(name = "CopyFundingSources", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        Boolean copyFundingSources,
        @WebParam(name = "CopySummaryData", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        Boolean copySummaryData,
        @WebParam(name = "CopyProjectNotes", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        Boolean copyProjectNotes,
        @WebParam(name = "CopyWBSMilestones", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        Boolean copyWBSMilestones,
        @WebParam(name = "CopyActivities", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        Boolean copyActivities,
        @WebParam(name = "CopyHighLevelResourcePlanning", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        Boolean copyHighLevelResourcePlanning,
        @WebParam(name = "CopyResourceAndRoleAssignments", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        Boolean copyResourceAndRoleAssignments,
        @WebParam(name = "CopyRelationships", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        Boolean copyRelationships,
        @WebParam(name = "CopyOnlyBetweenCopiedActivities", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        Boolean copyOnlyBetweenCopiedActivities,
        @WebParam(name = "CopyActivityExpenses", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        Boolean copyActivityExpenses,
        @WebParam(name = "CopyActivityCodes", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        Boolean copyActivityCodes,
        @WebParam(name = "CopyActivityNotes", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        Boolean copyActivityNotes,
        @WebParam(name = "CopyActivitySteps", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        Boolean copyActivitySteps,
        @WebParam(name = "CopyPastPeriodActuals", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        Boolean copyPastPeriodActuals,
        @WebParam(mode = WebParam.Mode.OUT, name = "ObjectId", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        javax.xml.ws.Holder<Integer> objectId1
    ) throws IntegrationFault;

    @WebMethod(operationName = "LoadActivityUDFValuesNewerThanBaseline", action = "LoadActivityUDFValuesNewerThanBaseline")
    @RequestWrapper(localName = "LoadActivityUDFValuesNewerThanBaseline", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2", className = "ccm.server.ws.p6.project.LoadActivityUDFValuesNewerThanBaseline")
    @ResponseWrapper(localName = "LoadActivityUDFValuesNewerThanBaselineResponse", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2", className = "ccm.server.ws.p6.project.LoadActivityUDFValuesNewerThanBaselineResponse")
    @WebResult(name = "UDFValueObjectIds", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
    public java.util.List<String> loadActivityUDFValuesNewerThanBaseline(

        @WebParam(name = "ObjectId", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        int objectId,
        @WebParam(name = "Fields", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        java.util.List<String> fields,
        @WebParam(name = "WhereClause", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        String whereClause,
        @WebParam(name = "OrderBy", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        String orderBy,
        @WebParam(name = "BaselineObjectId", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        int baselineObjectId
    ) throws IntegrationFault;

    @WebMethod(operationName = "CreateCopyAsTemplate", action = "CreateCopyAsTemplate")
    @RequestWrapper(localName = "CreateCopyAsTemplate", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2", className = "ccm.server.ws.p6.project.CreateCopyAsTemplate")
    @ResponseWrapper(localName = "CreateCopyAsTemplateResponse", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2", className = "ccm.server.ws.p6.project.CreateCopyAsTemplateResponse")
    public void createCopyAsTemplate(

        @WebParam(name = "ObjectId", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        int objectId,
        @WebParam(name = "EPSObjectId", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        int epsObjectId,
        @WebParam(name = "CopyRisks", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        Boolean copyRisks,
        @WebParam(name = "CopyIssuesThresholds", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        Boolean copyIssuesThresholds,
        @WebParam(name = "CopyReports", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        Boolean copyReports,
        @WebParam(name = "CopyProjectDocuments", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        Boolean copyProjectDocuments,
        @WebParam(name = "CopyFundingSources", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        Boolean copyFundingSources,
        @WebParam(name = "CopySummaryData", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        Boolean copySummaryData,
        @WebParam(name = "CopyProjectNotes", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        Boolean copyProjectNotes,
        @WebParam(name = "CopyActualToPlannedValues", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        Boolean copyActualToPlannedValues,
        @WebParam(name = "CopyWBSMilestones", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        Boolean copyWBSMilestones,
        @WebParam(name = "CopyActivities", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        Boolean copyActivities,
        @WebParam(name = "CopyHighLevelResourcePlanning", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        Boolean copyHighLevelResourcePlanning,
        @WebParam(name = "CopyResourceAndRoleAssignments", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        Boolean copyResourceAndRoleAssignments,
        @WebParam(name = "CopyRelationships", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        Boolean copyRelationships,
        @WebParam(name = "CopyOnlyBetweenCopiedActivities", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        Boolean copyOnlyBetweenCopiedActivities,
        @WebParam(name = "CopyActivityExpenses", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        Boolean copyActivityExpenses,
        @WebParam(name = "CopyActivityCodes", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        Boolean copyActivityCodes,
        @WebParam(name = "CopyActivityNotes", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        Boolean copyActivityNotes,
        @WebParam(name = "CopyActivitySteps", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        Boolean copyActivitySteps,
        @WebParam(name = "CopyPastPeriodActuals", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        Boolean copyPastPeriodActuals,
        @WebParam(mode = WebParam.Mode.OUT, name = "ObjectId", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        javax.xml.ws.Holder<Integer> objectId1
    ) throws IntegrationFault;

    @WebMethod(operationName = "CreateProjects", action = "CreateProjects")
    @RequestWrapper(localName = "CreateProjects", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2", className = "ccm.server.ws.p6.project.CreateProjects")
    @ResponseWrapper(localName = "CreateProjectsResponse", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2", className = "ccm.server.ws.p6.project.CreateProjectsResponse")
    @WebResult(name = "ObjectId", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
    public java.util.List<Integer> createProjects(

        @WebParam(name = "Project", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        java.util.List<ccm.server.ws.p6.project.Project> project
    ) throws IntegrationFault;

    @WebMethod(operationName = "ReadProjects", action = "ReadProjects")
    @RequestWrapper(localName = "ReadProjects", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2", className = "ccm.server.ws.p6.project.ReadProjects")
    @ResponseWrapper(localName = "ReadProjectsResponse", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2", className = "ccm.server.ws.p6.project.ReadProjectsResponse")
    @WebResult(name = "Project", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
    public java.util.List<ccm.server.ws.p6.project.Project> readProjects(

        @WebParam(name = "Field", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        java.util.List<ccm.server.ws.p6.project.ProjectFieldType> field,
        @WebParam(name = "Filter", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        String filter,
        @WebParam(name = "OrderBy", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        String orderBy
    ) throws IntegrationFault;

    @WebMethod(action = "getFieldLengthProject")
    @RequestWrapper(localName = "getFieldLengthProject", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2", className = "ccm.server.ws.p6.project.GetFieldLengthProject")
    @ResponseWrapper(localName = "getFieldLengthProjectResponse", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2", className = "ccm.server.ws.p6.project.GetFieldLengthProjectResponse")
    @WebResult(name = "Return", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
    public int getFieldLengthProject(

        @WebParam(name = "Field", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        String field
    ) throws IntegrationFault;

    @WebMethod(operationName = "CopyProjectAsReflection", action = "CopyProjectAsReflection")
    @RequestWrapper(localName = "CopyProjectAsReflection", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2", className = "ccm.server.ws.p6.project.CopyProjectAsReflection")
    @ResponseWrapper(localName = "CopyProjectAsReflectionResponse", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2", className = "ccm.server.ws.p6.project.CopyProjectAsReflectionResponse")
    public void copyProjectAsReflection(

        @WebParam(name = "ObjectId", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        int objectId,
        @WebParam(mode = WebParam.Mode.OUT, name = "ObjectId", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        javax.xml.ws.Holder<Integer> objectId1
    ) throws IntegrationFault;

    @WebMethod(operationName = "CopyBaseline", action = "CopyBaseline")
    @RequestWrapper(localName = "CopyBaseline", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2", className = "ccm.server.ws.p6.project.CopyBaseline")
    @ResponseWrapper(localName = "CopyBaselineResponse", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2", className = "ccm.server.ws.p6.project.CopyBaselineResponse")
    public void copyBaseline(

        @WebParam(name = "ObjectId", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        int objectId,
        @WebParam(name = "BaselineObjectId", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        int baselineObjectId,
        @WebParam(mode = WebParam.Mode.OUT, name = "ObjectId", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        javax.xml.ws.Holder<Integer> objectId1
    ) throws IntegrationFault;

    @WebMethod(operationName = "AssignProjectAsBaseline", action = "AssignProjectAsBaseline")
    @RequestWrapper(localName = "AssignProjectAsBaseline", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2", className = "ccm.server.ws.p6.project.AssignProjectAsBaseline")
    @ResponseWrapper(localName = "AssignProjectAsBaselineResponse", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2", className = "ccm.server.ws.p6.project.AssignProjectAsBaselineResponse")
    @WebResult(name = "BaselineProjectObjectId", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
    public int assignProjectAsBaseline(

        @WebParam(name = "OriginalProjectObjectId", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        int originalProjectObjectId,
        @WebParam(name = "TargetProjectObjectId", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        int targetProjectObjectId
    ) throws IntegrationFault;

    @WebMethod(operationName = "LoadActivitiesNewerThanBaseline", action = "LoadActivitiesNewerThanBaseline")
    @RequestWrapper(localName = "LoadActivitiesNewerThanBaseline", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2", className = "ccm.server.ws.p6.project.LoadActivitiesNewerThanBaseline")
    @ResponseWrapper(localName = "LoadActivitiesNewerThanBaselineResponse", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2", className = "ccm.server.ws.p6.project.LoadActivitiesNewerThanBaselineResponse")
    @WebResult(name = "ActivityObjectIds", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
    public java.util.List<String> loadActivitiesNewerThanBaseline(

        @WebParam(name = "ObjectId", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        int objectId,
        @WebParam(name = "Fields", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        java.util.List<String> fields,
        @WebParam(name = "WhereClause", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        String whereClause,
        @WebParam(name = "OrderBy", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        String orderBy,
        @WebParam(name = "BaselineObjectId", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        int baselineObjectId
    ) throws IntegrationFault;

    @WebMethod(operationName = "UpdateProjectPreferences", action = "UpdateProjectPreferences")
    @RequestWrapper(localName = "UpdateProjectPreferences", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2", className = "ccm.server.ws.p6.project.UpdateProjectPreferences")
    @ResponseWrapper(localName = "UpdateProjectPreferencesResponse", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2", className = "ccm.server.ws.p6.project.UpdateProjectPreferencesResponse")
    @WebResult(name = "Return", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
    public boolean updateProjectPreferences(

        @WebParam(name = "ObjectId", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        int objectId,
        @WebParam(name = "EnablePublication", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        Boolean enablePublication,
        @WebParam(name = "PublicationPriority", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        Integer publicationPriority,
        @WebParam(name = "LastPublishedOn", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        String lastPublishedOn,
        @WebParam(name = "PublishLevel", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        String publishLevel,
        @WebParam(name = "DeploymentNames", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        String deploymentNames,
        @WebParam(name = "DeleteDeployments", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        String deleteDeployments,
        @WebParam(name = "UnifierEnabledFlag", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        Boolean unifierEnabledFlag,
        @WebParam(name = "UnifierProjectNumber", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        String unifierProjectNumber,
        @WebParam(name = "UnifierProjectName", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        String unifierProjectName,
        @WebParam(name = "UnifierScheduleSheetName", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        String unifierScheduleSheetName,
        @WebParam(name = "UnifierDataMappingName", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        String unifierDataMappingName,
        @WebParam(name = "UnifierDeleteActivitiesFlag", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        Boolean unifierDeleteActivitiesFlag,
        @WebParam(name = "UnifierCBSTasksOnlyFlag", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        Boolean unifierCBSTasksOnlyFlag,
        @WebParam(name = "ProjectScheduleType", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        String projectScheduleType,
        @WebParam(name = "SyncWbsHierarchyFlag", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        Boolean syncWbsHierarchyFlag,
        @WebParam(name = "ScheduleWBSHierarchyType", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        String scheduleWBSHierarchyType,
        @WebParam(name = "WBSHierarchyLevels", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        Integer wbsHierarchyLevels,
        @WebParam(name = "EnableSummarization", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        Boolean enableSummarization,
        @WebParam(name = "SummaryLevel", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        String summaryLevel,
        @WebParam(name = "SummarizeToWBSLevel", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        Integer summarizeToWBSLevel,
        @WebParam(name = "LastSummarizedDate", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        String lastSummarizedDate,
        @WebParam(name = "HistoryLevel", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        String historyLevel,
        @WebParam(name = "HistoryInterval", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        String historyInterval
    ) throws IntegrationFault;

    @WebMethod(operationName = "LoadAllResources", action = "LoadAllResources")
    @RequestWrapper(localName = "LoadAllResources", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2", className = "ccm.server.ws.p6.project.LoadAllResources")
    @ResponseWrapper(localName = "LoadAllResourcesResponse", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2", className = "ccm.server.ws.p6.project.LoadAllResourcesResponse")
    @WebResult(name = "ResourceObjectIds", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
    public java.util.List<String> loadAllResources(

        @WebParam(name = "ObjectId", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        int objectId,
        @WebParam(name = "Fields", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        java.util.List<String> fields,
        @WebParam(name = "WhereClause", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        String whereClause,
        @WebParam(name = "OrderBy", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        String orderBy
    ) throws IntegrationFault;

    @WebMethod(operationName = "CopyProjectAsBaseline", action = "CopyProjectAsBaseline")
    @RequestWrapper(localName = "CopyProjectAsBaseline", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2", className = "ccm.server.ws.p6.project.CopyProjectAsBaseline")
    @ResponseWrapper(localName = "CopyProjectAsBaselineResponse", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2", className = "ccm.server.ws.p6.project.CopyProjectAsBaselineResponse")
    public void copyProjectAsBaseline(

        @WebParam(name = "ObjectId", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        int objectId,
        @WebParam(mode = WebParam.Mode.OUT, name = "ObjectId", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        javax.xml.ws.Holder<Integer> objectId1
    ) throws IntegrationFault;

    @WebMethod(operationName = "UpdateProjects", action = "UpdateProjects")
    @RequestWrapper(localName = "UpdateProjects", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2", className = "ccm.server.ws.p6.project.UpdateProjects")
    @ResponseWrapper(localName = "UpdateProjectsResponse", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2", className = "ccm.server.ws.p6.project.UpdateProjectsResponse")
    @WebResult(name = "Return", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
    public boolean updateProjects(

        @WebParam(name = "Project", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        java.util.List<ccm.server.ws.p6.project.Project> project
    ) throws IntegrationFault;

    @WebMethod(operationName = "CopyProject", action = "CopyProject")
    @RequestWrapper(localName = "CopyProject", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2", className = "ccm.server.ws.p6.project.CopyProject")
    @ResponseWrapper(localName = "CopyProjectResponse", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2", className = "ccm.server.ws.p6.project.CopyProjectResponse")
    public void copyProject(

        @WebParam(name = "ObjectId", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        int objectId,
        @WebParam(name = "EPSObjectId", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        int epsObjectId,
        @WebParam(name = "CopyRisks", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        Boolean copyRisks,
        @WebParam(name = "CopyIssuesThresholds", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        Boolean copyIssuesThresholds,
        @WebParam(name = "CopyReports", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        Boolean copyReports,
        @WebParam(name = "CopyProjectDocuments", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        Boolean copyProjectDocuments,
        @WebParam(name = "CopyFundingSources", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        Boolean copyFundingSources,
        @WebParam(name = "CopySummaryData", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        Boolean copySummaryData,
        @WebParam(name = "CopyProjectNotes", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        Boolean copyProjectNotes,
        @WebParam(name = "CopyWBSMilestones", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        Boolean copyWBSMilestones,
        @WebParam(name = "CopyActivities", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        Boolean copyActivities,
        @WebParam(name = "CopyHighLevelResourcePlanning", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        Boolean copyHighLevelResourcePlanning,
        @WebParam(name = "CopyResourceAndRoleAssignments", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        Boolean copyResourceAndRoleAssignments,
        @WebParam(name = "CopyRelationships", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        Boolean copyRelationships,
        @WebParam(name = "CopyOnlyBetweenCopiedActivities", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        Boolean copyOnlyBetweenCopiedActivities,
        @WebParam(name = "CopyActivityExpenses", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        Boolean copyActivityExpenses,
        @WebParam(name = "CopyActivityCodes", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        Boolean copyActivityCodes,
        @WebParam(name = "CopyActivityNotes", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        Boolean copyActivityNotes,
        @WebParam(name = "CopyActivitySteps", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        Boolean copyActivitySteps,
        @WebParam(name = "CopyPastPeriodActuals", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        Boolean copyPastPeriodActuals,
        @WebParam(mode = WebParam.Mode.OUT, name = "ObjectId", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        javax.xml.ws.Holder<Integer> objectId1
    ) throws IntegrationFault;

    @WebMethod(operationName = "CalculateProjectScore", action = "CalculateProjectScore")
    @RequestWrapper(localName = "CalculateProjectScore", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2", className = "ccm.server.ws.p6.project.CalculateProjectScore")
    @ResponseWrapper(localName = "CalculateProjectScoreResponse", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2", className = "ccm.server.ws.p6.project.CalculateProjectScoreResponse")
    @WebResult(name = "Score", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
    public int calculateProjectScore(

        @WebParam(name = "ProjectObjectId", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        int projectObjectId,
        @WebParam(name = "ProjectCodeTypeObjectId", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        java.util.List<Integer> projectCodeTypeObjectId
    ) throws IntegrationFault;
}
